// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDducgZoOs1VFkxxv9Fxlw2Milr7DtuHPs',
    appId: '1:775352442938:web:31583d9b3428d2f5245503',
    messagingSenderId: '775352442938',
    projectId: 'random-chat-6686d',
    authDomain: 'random-chat-6686d.firebaseapp.com',
    databaseURL: 'https://random-chat-6686d-default-rtdb.firebaseio.com',
    storageBucket: 'random-chat-6686d.firebasestorage.app',
    measurementId: 'G-22PS8DTQRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnwoaX8N48di5WRMtLtkjV_u3v3PiP0Qs',
    appId: '1:775352442938:android:fb5cc4288a50e3d6245503',
    messagingSenderId: '775352442938',
    projectId: 'random-chat-6686d',
    databaseURL: 'https://random-chat-6686d-default-rtdb.firebaseio.com',
    storageBucket: 'random-chat-6686d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_eXIvHT1KRD3YvcTfv32gBebu4Lik5c',
    appId: '1:775352442938:ios:2cb6cad8d0af76a4245503',
    messagingSenderId: '775352442938',
    projectId: 'random-chat-6686d',
    databaseURL: 'https://random-chat-6686d-default-rtdb.firebaseio.com',
    storageBucket: 'random-chat-6686d.firebasestorage.app',
    iosBundleId: 'com.chat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_eXIvHT1KRD3YvcTfv32gBebu4Lik5c',
    appId: '1:775352442938:ios:2cb6cad8d0af76a4245503',
    messagingSenderId: '775352442938',
    projectId: 'random-chat-6686d',
    databaseURL: 'https://random-chat-6686d-default-rtdb.firebaseio.com',
    storageBucket: 'random-chat-6686d.firebasestorage.app',
    iosBundleId: 'com.chat.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDducgZoOs1VFkxxv9Fxlw2Milr7DtuHPs',
    appId: '1:775352442938:web:6d8e0f5c1d5c6cf3245503',
    messagingSenderId: '775352442938',
    projectId: 'random-chat-6686d',
    authDomain: 'random-chat-6686d.firebaseapp.com',
    databaseURL: 'https://random-chat-6686d-default-rtdb.firebaseio.com',
    storageBucket: 'random-chat-6686d.firebasestorage.app',
    measurementId: 'G-K85YYDWV07',
  );

}